name: EntityTrackerFixer
authors: [Esmorall, Artel]

version: ${project.version}
main: net.minemora.entitytrackerfixer.Main
api-version: '1.13'

commands:
  entitytrackerfixer:
    aliases: [etf]
    permission: entitytrackerfixer.admin

permissions:
  entitytrackerfixer.admin:
    default: op